services:
  clips:
    build: .
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./var:/app/var
      # there's no real automatic way to mount media directories,
      # which sucks. You will need to do this yourself.
      - /mnt/ssd1_500/media-backup/media:/mnt/ssd1_500/media-backup/media
    command: ./app --port 8000 --var-dir /app/var --config-file /app/config.yaml

    networks:
      - site_network

networks:
  site_network:
    external: true
